
[[sect-quantities]]
== Quantitys

=== Basics

A Quantity has a value, units and dimensions with getter methods for them:

[source,java]
----
include::{basedir}/src/main/java/Examples.java[tag="quantitygetters"]
----

The value is a Number, so the precision and length of the Quantity is defined by the Number class (Is this true? Expand on implications).

=== Creating Quantitys

The normal method to create a Quantity was illustrated above:

[source,java]
----
include::{basedir}/src/main/java/Minimal.java[tag="main"]
----

Because Quantitys are immutable, arithmetic operations and converters also result in new Quantity objects.

The other way to create quantities is by parsing Strings (xref:sect-parsing[]).
This is normally only used when reading external input.

- Any others?

=== Methods

arithmetic - see xref:sect-arithmetic[]

`getScale()`::
  Is the unit relative (like CELSIUS)?
Can't think of a user application for this.

`toSystemUnit()`:
  Shorthand for `q.to(q.getSystemUnit())`:
Useful for converting to the base unit before using the primitive value (xref:sect-performance[]).

=== Utilty classes

Although they are not required by JSR-385, {product} contains several application classes based on Quantity:

QuantityRange::
  Has minimum and maximum Quantitys, with a single method `contains(final Quantity<Q> q)`.
See xref:{javadoc}/quantity/QuantityRange.html[javadoc] for details.

CompoundQuantity::
  Represents multi-radix quantities (like "1 hour, 5 min, 30 sec" or "6 ft, 3 in").
See xref:{javadoc}/quantity/CompoundQuantity.html[javadoc] for details.

- Should this be MixedQuantity?

