
[[sect-parsing]]
== Parsing

[WARNING]
According to the Javadocs, the parser should be configurable for the number-unit separator and the multiple-radix separators, but I can't get it to work.
The default <number><space>[prefix]<unit> works OK, so this is all I will describe until I work out what is going on.

[NOTE]
`SimpleQuantityFormat` contains a number formatter and a `SimpleUnitFormatter` so any description of unit handling in `SimpleQuantityFormat` covers `SimpleUnitFormat` as well.

`SimpleQuantityFormat` can interpret decimal numbers, rational numbers, unit symbols, compound units and SI prefixes.

For example:

[source,java,indent=2]
----
  SimpleQuantityFormat f = SimpleQuantityFormat.getInstance();
  String output = f.parse(input).toString();
----
//  String reparse = f.parse(output).toString();

|===
|Case |Input |Output

// exp=6 m equal=true equivalent=true reparse=6 m
|Simple
|[`6 m`]
|6 m
// exp=6 m equal=true equivalent=true reparse=6 m
|Extra space
|[`6       m`]
|6 m
// exp=11 kV equal=false equivalent=false reparse=11.3 kV
|Prefix
|[`11.3 kV`]
|11.3 kV
// exp=-1.6666666666666667 m equal=false equivalent=false reparse=-1.666666666666666666666666666666667 m
|Rational number
|[`-5÷3 m`]
|-1.666666666666666666666666666666667 m
// exp=11 N·m equal=true equivalent=true reparse=11 N·m
|Compound
|[`11 N·m`]
|11 N·m
// exp=6 m/s equal=true equivalent=true reparse=6 m/s
|Inverted
|[`6 m/s`]
|6 m/s
// exp=6 m/s² equal=true equivalent=true reparse=6 m/s²
|Inverted powers
|[`6 m/s²`]
|6 m/s²
// exp=1013 kg/m³ equal=true equivalent=true reparse=1013 kg/m³
|Repeated units
|[`1013 kg/m·m·m`]
|1013 kg/m³
// exp=null equal=false equivalent=false reparse=null
|Scientific
|[`6 m·s⁻²`]
|javax.measure.format.MeasurementParseException: Parse Error
// exp=null equal=false equivalent=false reparse=null
|Leading 1
|[`6 1/s`]
|javax.measure.format.MeasurementParseException: unexpected token INTEGER
|===

*Notes*

1. The prefix has no separator between it and the unit.

2. There must be a Unicode middle dot (not dot, full space or small space) between compound units.

3. Extra whitespace between the number and the unit is ignored.

4. To use numerals to specify powers, use the unicode superscript digits.

5. In all cases, the output can be toString()ed and reparsed, and the result is equal and equivalent to the first parse result.

6. If you have defined your own units, the parser can be extended to include them by:

.Registering a unit symbol
[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="extendparser"]
----

.Unicode symbols
[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="unicode"]
----

If a particular string will not parse, try creating it using `getQuantity()` then compare the string with the `quantity.toString()` output.

See xref:sect-puttingittogether[] for more details.


