
[[sect-quantities]]
== Quantitys

=== Basics

A Quantity has a value, units and dimensions with getter methods for them:

[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="quantitygetters"]
----

The value is a Number, so the precision and length of the Quantity is defined by the Number class (Is this true? Expand on implications).

=== Creating Quantitys

For completeness, the ways to create new Quantities are:

`Quantities.getQuantity`::
  The normal way to create a Quantity from primitives, as illustrated above.

Arithmetic::
  Because Quantitys are immutable, arithmetic operations result in new Quantity objects. (xref:sect-arithmetic[])

Conversion::
  Because Quantitys are immutable, converters also result in new Quantity objects. (xref:sect-convertingquanties[])

Parsing strings::
  This is normally only used when reading external input. (xref:sect-parsing[])

QuantityFactories::
  TBD (xref:sect-aspartofjsr[])

(De-)Serialisation::
  Yes (xref:sect-serialisation[])

=== Methods

Arithmetic operations - see xref:sect-arithmetic[]

`getScale()`::
  Is the unit relative (like CELSIUS)?
Can't think of a user application for this.

`toSystemUnit()`:
  Shorthand for `q.to(q.getSystemUnit())`:
Can't think of a user application for this.

=== Utilty classes

Although they are not part of JSR-385, {product} contains several application classes based on Quantity:

QuantityRange::
  Has low and high Quantitys, with a single method `contains(final Quantity<Q> q)`.
See xref:{javadoc}/quantity/QuantityRange.html[javadoc] for details.

CompoundQuantity::
  Represents multi-radix quantities (like "1 hour, 5 min, 30 sec" or "6 ft, 3 in").
See xref:{javadoc}/quantity/CompoundQuantity.html[javadoc] for details.

- Should this be MixedQuantity?

- I can't parse this.
