
[[sect-parsing]]
== Parsing

[WARNING]
According to the Javadocs, the parser should be configurable for the number-unit separator and the multiple-radix separators, but I can't get it to work.
The default <number><space>[prefix]<unit> works OK, so this is all I will describe until I work out what is going on.

[NOTE]
`SimpleQuantityFormat` contains a number formatter and a `SimpleUnitFormatter` so any description of unit handling in `SimpleQuantityFormat` covers `SimpleUnitFormat` as well.

`SimpleQuantityFormat` can interpret decimal numbers, rational numbers, unit symbols, compound units and SI prefixes.

For example:

[source,java]
----
include::{basedir}/src/main/java/Examples.java[tag="simpleformat"]
----

Note that the prefix has no separator between it and the unit, but there must be a full space (not dot, middle dot or small space) between compound units.

If you have defined your own units, it can be extended to include them by

[source,java]
----
include::{basedir}/src/main/java/Examples.java[tag="extendparser"]
----

If a particular string will not parse, try creating it using `getQuantity()` then compare the string with the `quantity.toString()` output.

See xref:sect-puttingittogether[] for more details.


