
[[sect-convertingquantities]]
== Converting Quantitys

=== to() method

Any Quantity can be converted into an _equivalent_ Quantity in different (but _commensurable_) units using the `Quantity.to()` method.
It results in a new `Quantity` Object:

[source,java]
----
include::{basedir}/src/main/java/Examples.java[tag="siprefixes"]
----

If the units are not commensurable, you will be prevented from doing so with a compile-time error (see xref:sect-errormessages[]).

[[sect-unitconverter]]
=== Converting primitives

If you have to convert many primitive numbers, use a  `UnitConverter`:

[source,java]
----
include::{basedir}/src/main/java/Examples.java[tag="converter"]
----

The (possibly complex) maths of working out the conversion factor occurs just once, and the subsequent conversions are as fast as possible.

This only converts primitives, so is a half-way house between manually controlling units and making everything a Quantity.
It can be used if the performance hit of Quantity is unacceptable (xref:sect-performance[]).
