
[[sect-objectproperties]]
== Java Object properties

////
- Random stuff that you may need when using Units and Quantitys as POJOs, but is not part of the API.

- Should be in the javadocs anyway, so not needed?

- Or break this up and put it where first relevant?
////

This section discusses properties of the UOM classes that are not specifically part of the API, but affect how you can use them.

=== Extendability

//  (check)

All Unit and Quantity classes are final.
They follow the Value-based Class pattern from https://docs.oracle.com/en/java/javase/15/docs/api/java.base/java/lang/doc-files/ValueBased.html#Value-basedClasses

////
Value-based Classes
Some classes, such as java.util.Optional and java.time.LocalDateTime, are value-based. Instances of a value-based class:
are final and immutable (though may contain references to mutable objects);
have implementations of equals, hashCode, and toString which are computed solely from the instance's state and not from its identity or the state of any other object or variable;
make no use of identity-sensitive operations such as reference equality (==) between instances, identity hash code of instances, or synchronization on an instances's intrinsic lock;
are considered equal solely based on equals(), not based on reference equality (==);
do not have accessible constructors, but are instead instantiated through factory methods which make no commitment as to the identity of returned instances;
are freely substitutable when equal, meaning that interchanging any two instances x and y that are equal according to equals() in any computation or method invocation should produce no visible change in behavior.
A program may produce unpredictable results if it attempts to distinguish two references to equal values of a value-based class, whether directly via reference equality or indirectly via an appeal to synchronization, identity hashing, serialization, or any other identity-sensitive mechanism. Use of such identity-sensitive operations on instances of value-based classes may have unpredictable effects and should be avoided.
////

=== Thread safety

Quantity and Unit instances are immutable therefore unconditionally thread safe.

=== Identity, equality and equivalence of Quantitys

To recap, Identity means the same Object (`==`), equality (`equals()`) means strict equality of different objects, and equivalence (`isEquivalentTo()`) means representing the same physical value irrespective of its units.

Identity is obvious, but is rarely used with Objects.

The definition of equality from the {product} Javadovcs is:

[quote]
____
public boolean equals​(Object obj)
Compares this quantity against the specified object for strict equality (same unit and same amount).
Similarly to the BigDecimal.equals(java.lang.Object) method which consider 2.0 and 2.00 as different objects because of different internal scales, quantities such as Quantities.getQuantity(3.0, KILOGRAM) Quantities.getQuantity(3, KILOGRAM) and Quantities.getQuantity("3 kg") might not be considered equals because of possible differences in their implementations.
____

The 'might' is a strong indication that the method should not be used, although in fact the example Quantitys are considered equal in {product}.

Equivalence is the normal test to use: it converts to common units, then compares the values.
This lets it work across units from different systems of units, providing they are commensurable.footnote:[I am at my Java limits here, and making it up]

Caveats:

- The amounts must be truly equal according to ({jdkjavadoc}/java/lang/Number.html[Number]): there is no method for "the same {plusminus} a bit".

- The arguments must be typed (eg `Quantity<Mass>` not `Quantity<?>`) which can make the method less convenient to use.

=== Ordering

Quantitys are not declared as comparable,footnote:[Why not?] but you can use them in Sorted Collections anyway.footnote:[Quantities.getQuantity() returns ComparableQuantity which does, and all creation methods seem to delegate to it]

.Sorting quantities
[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="collections"]
----

Sorting is by base value as you would hope.

If you want to make explicit comparisons, declare or cast your Quantitys to `ComparableQuantity`:

.Comparable
[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="comparable"]
----

You can use the Comparable.compareTo() directly as shown, but the class also has convenience methods 
`isLessThan()`, `isGreaterThanOrEqualTo()` etc.

[WARNING]
The test used in the comparator for "the same" is `isEquivalentTo()` but the `equals()` method is used when adding to Sets.
Equals is therefore not consistent with Comparable, and the general contract for Collections will be broken if you use Quantities in Sets.
(ref Bloch item X)

=== Serialisation

==== Using +java.io.Serializable+

`Quantity` is not serializable but `ComparableQuantity` is.
Does this mean that you have to hope that QuantityFactories obtained from other libraries produce Serializable as well?
Or recreate then using {product}? Head spinning.
The stored size is variable, roughly 20 to 60 bytes.

==== Using text

Yes, with some caveats.

The text (`Quantity.toString()`) form produced by a formatter is guaranteed to be convertible to and from the binary form without loss of precision.
That is:

[source,java,indent=2]
----
include::{basedir}/src/main/java/Examples.java[tag="text"]
----

This is required by the JSR (is it?), so should be true for any other implementation as well.

If you have defined your own units, either convert the quantities to built-in units before export, or distribute your program as well, otherwise the recipient will not be able to parse the output.

If you are restricted to ASCII-only files (ie no Unicode), use the ASCII flavour of +SimpleQuantityFormat+ (How? show example)

==== Using JavaBeans XML

Not currently implemented.
See {issue}/264[issue #264] and {issue}/266[issue #266].

